### ISSUE TITLE
Getting this template released

### ISSUE THREAD

**Issue by derberg** [asyncapi/php-template#151]
@emilianozublena hey, wanted to check with you what are your plans for this template. If you still want to maintain it, as I was thinking, basing on the fact that it got contribution and there are starts, that we should finally release it as official asyncapi template.

But of course it makes sense only if it is going to be maintained

**Comment by emilianozublena** [comment]
Sorry for the late response @derberg, trying to get back into a more active state around this template. I'd publish it ofc, i'll make sure to answer any potential issues/PR's back and also work around a few things that we can improve.

**Comment by derberg** [comment]
@emilianozublena in Poland we say "better late than never" 😆 

good to see you back and that you want to be more active here. I was recently approached by one guy from Poland concerned about the state of the template. I think he was willing to contribute 😄 

@Ferror good news, Emiliano is back 💪🏼 we probably brought him with our thoughts 😄 I suggest you open the issue and describe your ideas for improvements there.

And please folks, forget about yesterday's game. We let you @emilianozublena win because Lewandowski felt sorry for Messi not scoring the penalty. Normally Poland plays better football, at least I hope so 🤣

**Comment by emilianozublena** [comment]
Awesome to hear someone's willing to contribute, that'll make things easier for sure. Open to any PR's or even issues like this to discuss of things we need to change/improve and/or add :)

@derberg i saw messi and lewandoski arguing, i think that prbly he told messi that now they're even lol

**Comment by emilianozublena** [comment]
Should we close this issue and let @Ferror open a new one to start chatting about it? @derberg

**Comment by derberg** [comment]
I definitely recommend running a separate issue about possible contributions. But please leave this one open.  In the coming days I will contribute PR that will enable automated releases in this template.

Would be great if you could rename this repo from `asyncapi-php-template` to `php-template` as it is already under `asyncapi` and npm name will be `@asyncapi/php-template`
